# Generated by Django 6.0.1 on 2026-02-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_preferred_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preferred_time_slot',
        ),
    ]
