# Generated by Django 6.0.1 on 2026-02-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_preferred_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('video', 'Video Lesson'), ('article', 'Text Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('points_value', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_lessons', models.ManyToManyField(blank=True, to='core.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Correct'), ('multiple', 'Multiple Correct')], default='single', max_length=20)),
                ('appear_at_second', models.IntegerField()),
                ('time_limit_seconds', models.IntegerField(default=60)),
                ('points_value', models.IntegerField(default=5)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_skip', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='core.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.interactivemcq')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SelfLearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_self_paced', models.BooleanField(default=True)),
                ('estimated_total_hours', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('certificate_available', models.BooleanField(default=True)),
                ('access_duration_days', models.IntegerField(default=365)),
                ('max_attempts_per_quiz', models.IntegerField(default=3)),
                ('min_quiz_score', models.IntegerField(default=70)),
                ('require_final_exam', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_learning', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='self_learning_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.selflearningcourse'),
        ),
        migrations.CreateModel(
            name='StudentMCQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField(default=0)),
                ('response_time_seconds', models.IntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.interactivemcq')),
                ('selected_options', models.ManyToManyField(related_name='selected_in_responses', to='core.mcqoption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_responses', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.IntegerField(default=0)),
                ('completed_modules', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_progress', to='core.course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lesson')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('video_progress_seconds', models.IntegerField(default=0)),
                ('video_watch_duration', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('best_quiz_score', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
